### ISSUE TITLE
Dev console cmds could break game

### ISSUE THREAD

**Issue by LopezRoman** [MissionToPsyche/tungsten_12a_web_game-se#175]
If you are not careful certain cmds in the dev console could break the game, these should be caught exceptions 

![image](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/assets/54126100/f9100e9f-7290-4dec-85bf-d79e7699a105)

**Comment by JoshBenn** [comment]
> Just use "set scene x" with x being the scene. No need to use "in" anymore.

You didn't need to use in before 😏

**Comment by JoshBenn** [comment]
Resolved with [PR 191](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/pull/191)
