### ISSUE TITLE
Game crashes with certain conditions upon entering Combo2

### ISSUE THREAD

**Issue by JoshBenn** [MissionToPsyche/tungsten_12a_web_game-se#186]
After hitting a checkpoint in a previous point of the level and dying, once entering the cave for combo2 the game will crash.

**Comment by LopezRoman** [comment]
Issue was actually with player becoming a child object of the moving platform. Player character was being taken out of "do not destroy" and thus when trying to transition to combo 2, was destroyed. Issue resoled in PR #200
