### ISSUE TITLE
Reported: Overusing abilities causes the game to bug and all controls besides wasd to break

### ISSUE THREAD

**Issue by JoshBenn** [MissionToPsyche/tungsten_12a_web_game-se#187]
"Might have something to do with jump and right click"

Could be something with how the GRNS is scanning all of the available items in the scene?

**Comment by LopezRoman** [comment]
Can you explain "overusing abilities"? Do you mean using all the tools at the same time?

And regarding GRNS, keep in mind this tool references the cameras viewpoint in the scene to load and unload the sprites it finds so if you're flying through a scene with max thruster all while using the GRNS, I can image some wonky things might happen.

**Comment by JoshBenn** [comment]
Pressing them at / around the same time

**Comment by jmolive8** [comment]
I've not extensively tested this but I haven't been able to replicate this error. Maybe we've already accidently fixed it?

**Comment by LopezRoman** [comment]
did not work on
