### ISSUE TITLE
Combo2 Scene has an issue where the initial gap is too small or prevents the character from moving through

### ISSUE THREAD

**Issue by JoshBenn** [MissionToPsyche/tungsten_12a_web_game-se#193]
![image](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/assets/134667610/d60386ad-c7f4-4143-97ae-fc09649fb50f)

**Comment by mcmyers4** [comment]
You can get through it is just very tight. This was intentional so the player can walk over the gap and has to deliberately use the grns to find the pathway. Will see if I can adjust of wait for more player feedback
