### ISSUE TITLE
Player can enter walls

### ISSUE THREAD

**Issue by mcmyers4** [MissionToPsyche/tungsten_12a_web_game-se#228]
So far this has been seen on the emagnet level
![image](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/assets/122760299/00f3727f-3434-4a50-8f12-439008b01cd4)

![image](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/assets/122760299/85d6eb70-82f9-4f38-a00b-46a0f863bbde)

**Comment by LopezRoman** [comment]
Closing but will keep testing out in build version.
