### ISSUE TITLE
Music skips when going back to title screen and screen shows "no display" momentarily 

### ISSUE THREAD

**Issue by LopezRoman** [MissionToPsyche/tungsten_12a_web_game-se#242]

**Comment by LopezRoman** [comment]
Below is also reported in console:
![image](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/assets/54126100/7dfbcb59-6bfa-45cd-ac0c-9426b9f61d19)

More than likely from the player character being destroyed which drops camera and switches to Title Screen main camera which has audio listener.

**Comment by JoshBenn** [comment]
I think reordering when the scene is transitioned and when to destroy the player could fix this issue.  I did note this on the merge [here](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/pull/231#issuecomment-2024208511)

**Comment by jmolive8** [comment]
I've tried reordering that code and it doesn't seem to fix the issue. Unless I still don't have it ordered correctly:
![Screenshot 2024-03-31 230615](https://github.com/MissionToPsyche/tungsten_12a_web_game-se/assets/77370384/3628213f-a8fe-47b4-83a1-d426839db046)

Also another issue I've noticed with this is error is that when you press Start and get back into the game commands you put into the dev console no longer do anything.

**Comment by LopezRoman** [comment]
Does not seem to be an issue in build version of game
